server:
  port: 8000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-orders
          uri: lb://ms-orders
          predicates:
            - Path=/api/pedidos/**
        - id: ms-product
          uri: lb://ms-product
          predicates:
            - Path=/api/products/**
