server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/pedidos/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/products/**